name: forma_app

sdkPath: .fvm/flutter_sdk

packages:
  - flutter/**
  - ./

categories:
  features:
    - flutter/feature/**
  dataComponent:
    - flutter/component/**/data
  domainComponent:
    - flutter/component/**/domain

scripts:
  analyze:
    exec: dart analyze .

  buildRunner:
    run: dart run build_runner build --delete-conflicting-outputs
    exec:
      orderDependents: true

command:
  bootstrap:
    dependencies:
      injectable: ^2.5.0
      get_it: ^8.0.0
      dartz: ^0.10.1

      dio: ^5.7.0
      retrofit: ^4.4.1
      jiffy: ^6.3.1
      json_annotation: ^4.9.0
      json_serializable: ^6.8.0
      drift:
      drift_dev: ^2.20.3
      drift_flutter: ^0.2.0

      cupertino_icons: ^1.0.8
      flutter_svg: ^2.0.10+1
      collection: ^1.18.0
      flutter_bloc: ^8.1.6
      auto_route: ^9.2.2
      freezed_annotation: ^2.4.4
      flutter_screenutil: ^5.9.3

      geolocator: ^13.0.1
      pigeon: ^22.4.2
      flutter_background_service: ^5.0.10

    dev_dependencies:
      flutter_lints:
      build_runner:
      injectable_generator:
      retrofit_generator:
      auto_route_generator:

    hooks:
      post: melos run buildRunner

