name: forma_app
description: "Forma app"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  core_feature:
    path: flutter/feature/core

  home_feature:
    path: flutter/feature/home

  core_component_data:
    path: flutter/component/core/data

  sensor_component_data:
    path: flutter/component/sensor/data

  session_component_data:
    path: flutter/component/session/data

  auto_route: ^8.1.4
  injectable: ^2.3.2
  get_it: ^7.6.4
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner:
  injectable_generator:
  auto_route_generator:

flutter:
  uses-material-design: true
