name: forma_app
description: "Forma"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.9+10

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  core_feature:
    path: flutter/feature/core

  home_feature:
    path: flutter/feature/home

  tracking_feature:
    path: flutter/feature/tracking

  core_component_data:
    path: flutter/component/core/data

  sensor_component_data:
    path: flutter/component/sensor/data

  session_component_data:
    path: flutter/component/session/data

  auto_route: ^9.2.2
  injectable: ^2.5.0
  get_it: ^8.0.0
  flutter_screenutil: ^5.9.3
  drift: null
  drift_dev: ^2.20.3
  drift_flutter: ^0.2.0

  flutter_native_splash: ^2.4.3

dev_dependencies:
  flutter_lints: null
  build_runner: null
  injectable_generator: null
  auto_route_generator: null
  melos: ^6.2.0

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
