name: user_component_domain
description: User Component Domain

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  core_component_domain:
    path: ../../core/domain

  injectable: ^2.5.0
  get_it: ^8.0.0
  dartz: ^0.10.1
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_lints:
  build_runner:
  injectable_generator:
  freezed: ^2.4.1
  json_serializable: ^6.1.5
