name: session_component_domain
description: Session Component Domain

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  core_component_domain:
    path: ../../core/domain

  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner:
  injectable_generator:
  freezed: ^2.4.1
  json_serializable: ^6.1.5

flutter:
