name: home_feature
description: Home Feature

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  core_feature:
    path: ../core

  sensor_component_domain:
    path: ../../component/sensor/domain

  session_component_domain:
    path: ../../component/session/domain

  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner:
  injectable_generator:
  auto_route_generator:
  freezed: ^2.4.1

flutter:
  assets:
    - asset/
    - asset/icon/
