name: core_feature
description: Core feature

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  core_component_domain:
    path: ../../component/core/domain

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  collection: ^1.18.0
  flutter_bloc: ^8.1.6
  auto_route: ^9.2.2
  injectable: ^2.5.0
  get_it: ^8.0.0
  freezed_annotation: ^2.4.4
  flutter_screenutil: ^5.9.3

  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints:
  build_runner:
  injectable_generator:
  freezed: ^2.4.1
  auto_route_generator:

flutter:
  uses-material-design: true

  assets:
    - font/
    - asset/icon/

  fonts:
    - family: DM Sans
      fonts:
        - asset: font/DMSans-Regular.ttf
        - asset: font/DMSans-Black.ttf
          weight: 900
        - asset: font/DMSans-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: font/DMSans-Bold.ttf
          weight: 700
        - asset: font/DMSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: font/DMSans-ExtraBold.ttf
          weight: 800
        - asset: font/DMSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: font/DMSans-ExtraLight.ttf
          weight: 200
        - asset: font/DMSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: font/DMSans-Italic.ttf
          style: italic
        - asset: font/DMSans-Light.ttf
          weight: 300
        - asset: font/DMSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: font/DMSans-Medium.ttf
          weight: 500
        - asset: font/DMSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: font/DMSans-SemiBold.ttf
          weight: 600
        - asset: font/DMSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: font/DMSans-Thin.ttf
          weight: 100
        - asset: font/DMSans-ThinItalic.ttf
          weight: 100
          style: italic

flutter_intl:
  enabled: true
  arb-dir: flutter/feature/core/lib/l10n
  output-dir: flutter/feature/core/lib/generated
  template-arb-file: intl_en_US.arb
  main_locale: en_US
